/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorial: [
    {
      type: 'autogenerated',
      dirName: 'tutorial',
    },
  ],
  contracts: [
    {
      type: 'category',
      label: 'Aptos',
      collapsed: false,
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'contracts/Aptos/contracts',
        },
        {
          type: 'category',
          label: 'Swap',
          items: [
            'contracts/Aptos/Swap/swap_api',
            'contracts/Aptos/Swap/swap_resources',
            'contracts/Aptos/Swap/swap_events',
            'contracts/Aptos/Swap/swap_examples',
          ],
          collapsed: true,
        },
        {
          type: 'category',
          label: 'MasterChef',
          items: [
            'contracts/Aptos/MasterChef/masterchef_api',
            'contracts/Aptos/MasterChef/masterchef_resources',
            'contracts/Aptos/MasterChef/masterchef_event',
          ],
          collapsed: true,
        },
      ],
    },
    {
      type: 'category',
      label: 'Sui',
      collapsed: false,
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'contracts/Sui/contracts',
        },
        {
          type: 'category',
          label: 'Swap',
          items: [
            'contracts/Sui/Swap/swap_api',
            'contracts/Sui/Swap/swap_resources',
            'contracts/Sui/Swap/swap_events',
            'contracts/Sui/Swap/swap_examples',
          ],
          collapsed: true,
        },
      ],
    },
  ],
  sdk: [
    {
      type: 'doc',
      label: 'Overview',
      id: 'sdk/sdk',
    },
  ],
  updates: [
    {
      type: 'autogenerated',
      dirName: 'updates',
    },
  ],
};

module.exports = sidebars;
